# Generated by Django 4.2.3 on 2023-07-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0013_alter_company_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contactNumber", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("vehicleMake", models.CharField(max_length=20)),
                ("vehicleRegNumber", models.CharField(max_length=10)),
                ("breakdownIssue", models.TextField()),
                ("location", models.TextField()),
                ("comments", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
