# Generated by Django 4.2.3 on 2023-07-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0019_alter_accounts_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
