# Generated by Django 4.2.3 on 2023-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0021_alter_vehicles_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.IntegerField(),
        ),
    ]
