# Generated by Django 4.2.3 on 2023-07-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0023_accounttypes_create_date_alter_company_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
