# Generated by Django 4.2.3 on 2023-07-22 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0027_alter_dispatchstatus_dispatch_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchentry',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='dispatchentry',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='dispatchentry',
            name='payment_status',
        ),
    ]
