# Generated by Django 4.2.3 on 2023-07-22 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0028_remove_dispatchentry_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='dispatch_entry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='A2Zbackend.dispatchentry'),
        ),
    ]
