# Generated by Django 4.2.3 on 2023-07-22 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0029_alter_cases_dispatch_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchentry',
            name='asset_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='A2Zbackend.dispatchentryassets'),
        ),
        migrations.AlterField(
            model_name='dispatchentry',
            name='case_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='A2Zbackend.cases'),
        ),
    ]
