# Generated by Django 4.2.3 on 2023-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0031_alter_dispatchentry_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchentry',
            name='ata',
            field=models.DateTimeField(null=True),
        ),
    ]
